title: CCG的个人小站
author: ccgccc
email: ccgcccccccccc@gmai.com
description:
  什么他娘的精锐，
  老子打的就是精锐！

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ccgccc # DO NOT include the @ character, or else the build will fail!

# show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
